# Generated by Django 4.0.5 on 2022-10-27 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HouseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('image', models.ImageField(blank=True, upload_to='house_images')),
                ('price', models.CharField(blank=True, max_length=50)),
                ('area', models.CharField(blank=True, max_length=60)),
                ('description', models.TextField(max_length=400)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.houselocation')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.housetype')),
            ],
        ),
    ]
