# Generated by Django 4.0.5 on 2022-10-27 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housetype',
            old_name='type',
            new_name='type_house',
        ),
    ]
